name: Integration testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install git+https://github.com/larsvonschaff/Django-mockingbird.git#egg=djangomockingbird
        git checkout ${GITHUB_REF##*/}
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=mlprepare" >> $GITHUB_ENV     
    - name: Clone the project
      run: |
          git clone https://github.com/larsvonschaff/Django-mockingbird-test-app
          cd Django-mockingbird-test-app
          python manage.py test
